// Contexte régional pour le contenu pSEO — 13 régions métropolitaines
// Chaque région a un contexte spécifique par catégorie de déchet

export interface RegionContent {
    name: string;
    gravats: string;
    encombrants: string;
    dechets_verts: string;
    dib: string;
}

export const regionsContent: Record<string, RegionContent> = {
    "Île-de-France": {
        name: "Île-de-France",
        gravats: "En Île-de-France, la densité urbaine et les réglementations strictes d'occupation du domaine public rendent la logistique de pose de benne plus complexe qu'ailleurs. La majorité des communes franciliennes exigent un arrêté de voirie pour toute benne posée sur la voie publique, avec un délai moyen de 10 jours ouvrés. Les constructions haussmanniennes et les immeubles en pierre de taille génèrent des gravats particulièrement lourds et denses.",
        encombrants: "L'Île-de-France est la région où la demande de bennes pour encombrants est la plus forte, notamment lors des déménagements (plus de 500 000 déménagements par an en région parisienne). Les contraintes de stationnement et de circulation imposent souvent une livraison tôt le matin. Dans les zones denses, les bennes 3m³ sont privilégiées car elles occupent une seule place de stationnement.",
        dechets_verts: "Malgré son image urbaine, l'Île-de-France possède de nombreuses zones pavillonnaires (Yvelines, Essonne, Val-d'Oise) où les jardins de taille moyenne génèrent un volume important de déchets verts, notamment au printemps et à l'automne. Les déchetteries franciliennes sont souvent saturées le week-end, rendant la benne particulièrement pratique.",
        dib: "L'Île-de-France concentre près de 25% de l'activité économique nationale. Les chantiers de bureaux, commerces et locaux d'activité génèrent des volumes considérables de DIB. Les entreprises franciliennes sont soumises au « Schéma régional de gestion des déchets du BTP » qui impose une traçabilité stricte des déchets via les bordereaux de suivi."
    },
    "Auvergne-Rhône-Alpes": {
        name: "Auvergne-Rhône-Alpes",
        gravats: "En Auvergne-Rhône-Alpes, le parc immobilier mêle constructions de montagne (pierre et bois) et urbanisme moderne dans les grandes agglomérations. À Lyon, Grenoble et Saint-Étienne, les chantiers de rénovation du bâti ancien génèrent des gravats composés de pierre calcaire, de pisé (terre crue) et de tuiles mécaniques. Les centres ISDI de la région sont bien répartis, facilitant le traitement des gravats.",
        encombrants: "Deuxième région la plus peuplée de France, Auvergne-Rhône-Alpes connaît un renouvellement constant du mobilier dans ses grandes agglomérations. Les stations de ski (Savoie, Haute-Savoie) génèrent également un pic de demande pour l'évacuation d'encombrants lors de la rénovation des locations saisonnières, traditionnellement entre mai et octobre.",
        dechets_verts: "La diversité climatique de la région — des plaines du Rhône aux alpages — crée des besoins variés en évacuation de déchets verts. Dans les zones de plaine (Ain, Loire), les jardins et exploitations agricoles produisent des volumes importants de tailles et d'élagages. En altitude, la saison de jardinage est concentrée de mai à septembre, créant un pic de demande estival.",
        dib: "Auvergne-Rhône-Alpes est un pôle industriel majeur (Vallée de la Chimie, Techtera, pôle mécanique). Les artisans et PME de la région, notamment dans le secteur du BTP et de la menuiserie, sont de gros producteurs de DIB. La politique régionale de valorisation des déchets encourage le tri à la source, ce qui rend les bennes mono-matière particulièrement adaptées."
    },
    "Nouvelle-Aquitaine": {
        name: "Nouvelle-Aquitaine",
        gravats: "La Nouvelle-Aquitaine possède un patrimoine bâti très diversifié, des maisons en pierre blonde du Périgord aux constructions en brique du Pays basque. Les gravats issus de ces rénovations nécessitent souvent un tri spécifique. La région connaît un dynamisme immobilier important, notamment sur la façade atlantique (Bordeaux, La Rochelle, Bayonne), où les chantiers de démolition-reconstruction sont fréquents.",
        encombrants: "Première région de France par sa superficie, la Nouvelle-Aquitaine compte de nombreuses résidences secondaires, notamment sur le littoral atlantique et dans le Périgord. Les débarras de maisons héritées et les vidages de résidences saisonnières représentent une part importante de la demande de bennes pour encombrants, avec un pic marqué au printemps et en début d'automne.",
        dechets_verts: "Le climat atlantique de la Nouvelle-Aquitaine, doux et humide, favorise une végétation luxuriante qui nécessite un entretien régulier. Les jardins de la région sont parmi les plus productifs en déchets verts de France, avec une saison d'élagage qui s'étend de mars à novembre. Les pins maritimes des Landes génèrent également des volumes importants de branches et d'aiguilles après les tempêtes hivernales.",
        dib: "La Nouvelle-Aquitaine est un territoire de PME et d'artisanat, avec un tissu économique dense dans le bois (filière pin maritime), l'agroalimentaire et la construction. Les entreprises de la région bénéficient du réseau des plateformes de valorisation des déchets du BTP mises en place par la CERC Nouvelle-Aquitaine, facilitant le recyclage des DIB."
    },
    "Occitanie": {
        name: "Occitanie",
        gravats: "L'Occitanie associe le bassin méditerranéen, les contreforts pyrénéens et les causses du Massif central. Les constructions en pierre calcaire du Languedoc et en galets du Roussillon génèrent des gravats denses. À Toulouse et Montpellier, les programmes de rénovation urbaine et la forte croissance démographique alimentent une demande soutenue de bennes pour gravats.",
        encombrants: "Région en forte croissance démographique, l'Occitanie attire de nombreux nouveaux résidents, ce qui génère des volumes importants de déménagements et donc de meubles à évacuer. Les villes de Toulouse, Montpellier et Nîmes connaissent un marché immobilier dynamique où les débarras d'appartements avant revente ou relocation sont fréquents.",
        dechets_verts: "Le climat méditerranéen de l'est de la région et le climat continental de l'ouest créent des besoins d'entretien paysager variés. Les platanes, oliviers et cyprès caractéristiques du Midi produisent des volumes de taille importants. Le risque incendie dans les départements méditerranéens (Hérault, Aude, Pyrénées-Orientales) impose un débroussaillage obligatoire dans un rayon de 50m autour des habitations.",
        dib: "L'Occitanie, avec Airbus à Toulouse et le pôle aéronautique, est un bassin industriel de premier plan. Les sous-traitants et artisans de la filière génèrent des DIB spécifiques (composites, métaux légers, emballages industriels). La région dispose d'un réseau dense de plateformes de tri-valorisation pour les déchets professionnels."
    },
    "Hauts-de-France": {
        name: "Hauts-de-France",
        gravats: "Les Hauts-de-France possèdent un parc immobilier ancien, notamment dans les corons du bassin minier et les maisons en brique rouge caractéristiques de la région. La rénovation thermique de ces logements anciens, souvent encouragée par les aides régionales, génère des volumes importants de gravats (briques, enduits, carrelages). Les centres de valorisation des inertes sont bien répartis dans la région.",
        encombrants: "Région densément peuplée, les Hauts-de-France connaissent un taux de rotation de logements élevé, générant une demande constante pour l'évacuation d'encombrants. Les marchés aux puces et braderies, tradition régionale, ne suffisent pas à absorber les volumes de meubles à évacuer. La métropole lilloise, en particulier, voit une forte demande de bennes de 10 à 20m³ pour les débarras d'appartements.",
        dechets_verts: "Les Hauts-de-France bénéficient d'un climat propice aux jardins, avec des précipitations bien réparties sur l'année. Les haies bocagères de l'Artois, les jardins familiaux du bassin minier et les parcs des maisons bourgeoises picardes produisent un volume régulier de déchets verts. La taille des haies et l'élagage des arbres d'ornement constituent la majorité des besoins.",
        dib: "Ancien bassin industriel en reconversion, les Hauts-de-France voient se multiplier les chantiers de réhabilitation de friches industrielles et commerciales. Ces projets génèrent des volumes considérables de DIB mixtes. La politique régionale de l'économie circulaire, portée par le réseau REV3, encourage fortement le tri et la valorisation des déchets d'activité."
    },
    "Provence-Alpes-Côte d'Azur": {
        name: "Provence-Alpes-Côte d'Azur",
        gravats: "En PACA, les constructions en pierre calcaire, les tuiles canal et les enduits traditionnels dominent le bâti ancien. La forte pression immobilière sur le littoral azuréen et dans les villages provençaux génère de nombreux chantiers de démolition-reconstruction. Les gravats doivent être acheminés vers les ISDI de la région, dont certains commencent à atteindre des seuils de saturation, ce qui peut impacter les délais de traitement.",
        encombrants: "PACA compte un nombre important de résidences secondaires, notamment sur la Côte d'Azur et en Luberon. Les propriétaires rénovent et renouvellent régulièrement le mobilier de ces biens, créant un flux saisonnier d'encombrants. La période de mai à septembre concentre près de 60% des demandes de bennes pour encombrants dans la région.",
        dechets_verts: "Le climat méditerranéen de PACA impose un débroussaillage obligatoire (OLD) dans un rayon de 50 mètres autour de toute habitation dans les communes classées à risque incendie. Cette obligation légale, renforcée chaque année, génère des volumes considérables de déchets verts. Les essences méditerranéennes (pin d'Alep, chêne vert, genévrier) produisent un bois sec et volumineux à évacuer.",
        dib: "La région PACA, avec le port de Marseille-Fos et le pôle pétrochimique de Berre, est un bassin industriel important. Les artisans et commerçants de la bande littorale génèrent des DIB variés. La spécificité de la région est la présence de filières de valorisation spécialisées (recyclage du bois en biomasse, valorisation des métaux), qui permettent souvent de réduire le coût de traitement des DIB triés."
    },
    "Grand Est": {
        name: "Grand Est",
        gravats: "Le Grand Est se distingue par la diversité de son patrimoine bâti : colombages alsaciens, pierre de Jaumont en Lorraine, pierres de taille en Champagne. La rénovation de ces bâtiments traditionnels génère des gravats spécifiques, parfois nécessitant un tri particulier. Les hivers rigoureux limitent la saison des chantiers extérieurs, concentrant la demande de bennes sur la période d'avril à octobre.",
        encombrants: "Le Grand Est, avec ses grandes agglomérations (Strasbourg, Metz, Nancy, Reims), connaît une forte activité de déménagements, notamment liée à la mobilité étudiante et professionnelle. Les logements anciens des centres-villes sont régulièrement vidés et réaménagés. La proximité de l'Allemagne et du Luxembourg influence les standards d'ameublement, accélérant le renouvellement du mobilier.",
        dechets_verts: "Le Grand Est possède d'importantes surfaces boisées et forestières, en particulier dans les Vosges et en forêt d'Argonne. Les jardins et vergers de la région, soumis à un climat continental avec de fortes amplitudes thermiques, nécessitent un entretien saisonnier intensif. La taille des arbres fruitiers (mirabelliers, quetschiers) est une tradition régionale qui génère des volumes réguliers de branchages.",
        dib: "Le Grand Est est une région industrielle diversifiée : automobile (Peugeot à Mulhouse), verrerie (Baccarat), bois (filière vosgienne) et agroalimentaire (champagne). Ces filières produisent des DIB spécifiques. Le réseau de déchetteries professionnelles est particulièrement dense dans la région, facilitant l'accès aux solutions de tri-valorisation pour les artisans."
    },
    "Pays de la Loire": {
        name: "Pays de la Loire",
        gravats: "En Pays de la Loire, les constructions traditionnelles en tuffeau (pierre blanche de Loire), en schiste ardoisier (Maine) et en granit (Vendée) produisent des gravats de nature variée. La région, en forte croissance démographique autour de Nantes et de la côte vendéenne, connaît une activité soutenue de construction neuve et de rénovation du bâti ancien, alimentant une demande constante de bennes pour gravats.",
        encombrants: "Les Pays de la Loire, avec une croissance de population parmi les plus fortes de France, voient affluer de nouveaux résidents qui emménagent et déménagent fréquemment. La côte atlantique (La Baule, Les Sables-d'Olonne, Saint-Jean-de-Monts) compte de nombreuses résidences secondaires dont le mobilier est renouvelé régulièrement, générant des flux importants d'encombrants à évacuer.",
        dechets_verts: "Le climat doux et humide des Pays de la Loire, tempéré par l'influence atlantique, est propice à une végétation abondante. La région est l'une des premières productrices horticoles de France, et les jardins privés bénéficient de conditions de croissance exceptionnelles. Les tontes de mars à novembre et les tailles de haies de thuyas, très répandues, génèrent des volumes conséquents de déchets verts.",
        dib: "Les Pays de la Loire se distinguent par un tissu d'artisans et de PME dans la construction navale (Saint-Nazaire), l'agroalimentaire (Maine-et-Loire) et le bâtiment. Les professionnels de la région bénéficient du réseau de plateformes de valorisation des déchets du BTP, avec des centres de tri adaptés aux DIB de chantier (bois, métal, plâtre)."
    },
    "Bretagne": {
        name: "Bretagne",
        gravats: "En Bretagne, le granit et le schiste dominent les constructions traditionnelles, produisant des gravats particulièrement lourds et denses. La rénovation des longères bretonnes et des maisons en pierre génère des volumes importants de matériaux inertes. Les conditions météorologiques (pluie, vent) imposent de protéger la benne avec une bâche pour éviter l'accumulation d'eau, qui alourdirait considérablement la charge.",
        encombrants: "La Bretagne, région attractive, connaît un flux régulier de déménagements. Les villes de Rennes, Brest et Lorient voient une forte demande de bennes pour le vidage de logements. La tradition des vide-greniers bretons, très populaires au printemps et en été, n'absorbe qu'une partie des meubles à évacuer. Les bennes encombrants 10 à 20m³ sont les plus demandées dans la région.",
        dechets_verts: "Le climat océanique breton, doux et humide, favorise une croissance végétale rapide et abondante tout au long de l'année. Les haies bocagères, caractéristiques du paysage breton, nécessitent une taille régulière et produisent des volumes importants de branchages. Les jardins bretons, rarement au repos grâce au climat clément, génèrent des déchets verts presque 10 mois par an.",
        dib: "La Bretagne, terre d'artisanat et de PME, concentre ses activités dans l'agroalimentaire, la construction et la pêche. Les entreprises de la région produisent des DIB variés (emballages agroalimentaires, palettes bois, plastiques agricoles). Le réseau de recyclage breton, structuré autour d'Éco-organismes comme Paprec et Suez, offre des solutions de valorisation compétitives."
    },
    "Normandie": {
        name: "Normandie",
        gravats: "La Normandie présente un patrimoine bâti varié : colombages dans le Pays d'Auge, pierre de Caen en Calvados, silex en Haute-Normandie. Les travaux de rénovation de ces bâtiments anciens génèrent des gravats de composition spécifique. La région bénéficie d'un réseau de centres ISDI bien développé, héritage de l'important effort de reconstruction d'après-guerre.",
        encombrants: "La Normandie, avec sa proximité de Paris, accueille de nombreux néo-ruraux qui rénovent des corps de ferme et des maisons de caractère. Ces rénovations impliquent souvent un débarras complet avant travaux. Les stations balnéaires (Deauville, Étretat, Granville) connaissent aussi un pic de demande saisonnier pour l'évacuation d'encombrants lors de la rénovation des locations estivales.",
        dechets_verts: "Le climat normand, tempéré et humide, est l'un des plus favorables à la croissance végétale en France. Les bocages normands, les vergers de pommiers à cidre et les jardins paysagers produisent un volume considérable de déchets verts. La taille des pommiers, tradition régionale, se pratique de décembre à mars et génère des branchages denses qui nécessitent une benne adaptée.",
        dib: "Le tissu économique normand, marqué par l'industrie automobile (Renault à Cléon, PSA à Poissy), la pétrochimie (Le Havre) et l'agroalimentaire, génère des DIB diversifiés. Les artisans du bâtiment, nombreux dans la région en raison de l'important parc de logements anciens à rénover, sont des utilisateurs réguliers de bennes DIB pour leurs chantiers multi-matériaux."
    },
    "Bourgogne-Franche-Comté": {
        name: "Bourgogne-Franche-Comté",
        gravats: "En Bourgogne-Franche-Comté, les constructions traditionnelles en pierre calcaire (Bourgogne) et en pierre de Comté produisent des gravats particulièrement lourds. La rénovation des maisons viticoles de la Côte-d'Or et des fermes comtoises est une activité soutenue. Le climat continental, avec des hivers rigoureux et des périodes de gel, concentre les chantiers entre avril et novembre, créant un pic saisonnier de demande de bennes.",
        encombrants: "Bourgogne-Franche-Comté, région à dominante rurale, voit de nombreuses successions de propriétés familiales qui nécessitent un débarras complet. Les maisons de village et corps de ferme, souvent transmis de génération en génération, accumulent mobilier ancien et objets divers. La benne 20 à 30m³ est fréquemment demandée pour les vidages de greniers et de dépendances.",
        dechets_verts: "Les vignobles bourguignons et les forêts comtoises génèrent des volumes spécifiques de déchets verts. La taille annuelle des vignes produit des sarments qui, bien que souvent brûlés traditionnellement, doivent de plus en plus être évacués conformément aux nouvelles réglementations environnementales. Les jardins de la région, marqués par un sol calcaire propice aux haies et arbustes, nécessitent un entretien régulier.",
        dib: "La Franche-Comté, avec ses PME spécialisées dans la micromécanique (Besançon), la lunetterie (Morez) et le bois (Jura), produit des DIB de nature variée. En Bourgogne, les activités viticoles et les métiers de bouche génèrent des emballages et des déchets d'activité spécifiques. Le réseau local de recycleurs, bien structuré mais moins dense qu'en Île-de-France, impose parfois des distances de transport plus longues."
    },
    "Centre-Val de Loire": {
        name: "Centre-Val de Loire",
        gravats: "Le Centre-Val de Loire se distingue par ses constructions en tuffeau, la pierre blanche emblématique des châteaux de la Loire. La rénovation de ce patrimoine historique et résidentiel génère des gravats nobles mais fragiles, nécessitant un transport soigneux. Les zones périurbaines de Tours, Orléans et Blois connaissent un développement immobilier actif qui alimente la demande de bennes pour gravats de construction neuve.",
        encombrants: "Le Centre-Val de Loire, avec ses villes moyennes et ses zones pavillonnaires, voit une demande régulière de bennes encombrants pour les déménagements et les rénovations de maisons individuelles. Les propriétés de la vallée de la Loire, souvent spacieuses, accumulent du mobilier au fil des années. Les débarras de caves et de greniers représentent une part significative des demandes.",
        dechets_verts: "Les parcs et jardins du Centre-Val de Loire, inspires par la tradition des jardins à la française, sont parmi les plus entretenus de France. Les espaces verts des propriétés ligériennes, les allées de platanes et les haies de buis nécessitent un entretien régulier. La pyrale du buis, qui sévit dans la région depuis 2018, a imposé l'arrachage de nombreux arbustes, générant des besoins ponctuels de bennes.",
        dib: "Le Centre-Val de Loire, avec un tissu économique diversifié (cosmétique à Chartres, pharmacie à Tours, logistique à Orléans), produit des DIB variés. Les zones d'activité de la région, situées le long de l'axe ligérien, bénéficient d'un bon accès aux plateformes de tri-valorisation. Les artisans locaux, nombreux dans la rénovation du bâti ancien, utilisent régulièrement des bennes DIB multi-matériaux."
    },
    "Corse": {
        name: "Corse",
        gravats: "En Corse, les constructions en granit et en schiste produisent des gravats extrêmement lourds et denses. L'insularité de la Corse pose un défi logistique spécifique : les centres de traitement des gravats sont moins nombreux qu'en métropole continentale, et les distances de transport peuvent impacter le coût final. Les chantiers dans les villages de montagne (Balagne, Castagniccia) nécessitent parfois des bennes de plus petit format en raison de l'étroitesse des voies d'accès.",
        encombrants: "L'île de beauté, avec son parc de résidences secondaires et ses locations saisonnières, connaît un pic de demande pour l'évacuation d'encombrants en mai-juin (préparation de la saison estivale) et en octobre (fin de saison). Les contraintes logistiques insulaires (ferries, routes de montagne) peuvent allonger les délais de livraison et de récupération des bennes dans les communes isolées.",
        dechets_verts: "Le maquis corse, végétation méditerranéenne dense et résistante, impose un débroussaillage obligatoire autour des habitations en raison du risque incendie élevé. Les propriétaires doivent maintenir une bande de 50 mètres dégagée autour de leur habitation. Cette obligation génère des volumes importants de déchets verts, surtout au printemps et à l'automne. Les essences locales (maquis, châtaigniers, oliviers) produisent un bois dense et volumineux.",
        dib: "Le tissu économique corse, dominé par le BTP, le tourisme et l'artisanat, génère des DIB concentrés dans les zones côtières urbanisées (Ajaccio, Bastia, Porto-Vecchio). L'insularité impose une gestion des déchets spécifique : les capacités de stockage et de traitement sont limitées, ce qui rend le tri à la source d'autant plus important pour réduire les volumes mis en décharge."
    },
};
